apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deploy
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - name: user-container
          image: 586639730662.dkr.ecr.ap-northeast-2.amazonaws.com/user:2026-03-08-02-17-53